// マスタデータ
            const mockMadnessList = [
                {
                    madnessId: "nm-1",
                    version: "new",
                    world: "Classic",
                    titleJa: "疑心暗鬼",
                    titleEn: "Thought Attack",
                    trigger: "自分以外のキャラクターがファンブルを起こす。",
                    desc: "周囲の人物に対して疑惑が高まる。誰かが、あなたを裏切っている！自分以外のPCの中から目標を1人を選ぶ。目標に2点のダメージを与える。",
                },
                {
                    madnessId: "nm-2",
                    version: "new",
                    world: "Classic",
                    titleJa: "暴力衝動",
                    titleEn: "Violence Impulse",
                    trigger: "誰か（自分を含む）がダメージを受ける。",
                    desc: "血だ！とにかくお前は誰かを傷つけたい。好きなPCの中から目標を1人を 選ぶ。目標に1点のダメージを与える。",
                },
                {
                    madnessId: "nm-3",
                    version: "new",
                    world: "Classic",
                    titleJa: "敵か味方か",
                    titleEn: "Friend or Foe",
                    trigger: "自分がダメージを受ける。",
                    desc: "味方以外は全員敵だ。あなたに好意をしめさない人間は、全員死ね！自分に対してプラスの【感情】を持っていないキャラクター全員（自分は除く）を目標に選ぶ。目標に1点のダメージを与える。",
                },
                {
                    madnessId: "nm-4",
                    version: "new",
                    world: "Classic",
                    titleJa: "裏切り",
                    titleEn: "Double-cross",
                    trigger: "自分以外の誰かが【狂気】を公開する。",
                    desc: "このまま、こんな連中と一緒にいていいんだろうか？こいつらのせいで、こんな目に遭ってるんじゃないのか！？自分以外のキャラクター全員を目標に選ぶ。目標に1点のダメージを与える。",
                },
                {
                    madnessId: "nm-5",
                    version: "new",
                    world: "Classic",
                    titleJa: "逆恨み",
                    titleEn: "Unjustified Resentment",
                    trigger:
                        "自分以外の誰かが、自分以外のキャラクターにプラスの【感情】を獲得する。",
                    desc: "あなたは、自分を差し置いて、誰かが誰かと仲良くしているのが許せない。自分に対してプラスの【感情】を持っていないキャラクター全員（自分は除く）を目標に選ぶ。目標に1点のダメージを与える。",
                },
                {
                    madnessId: "nm-6",
                    version: "new",
                    world: "Classic",
                    titleJa: "疎外感",
                    titleEn: "Alienation",
                    trigger: "即座。",
                    desc: "みんながあなたを嫌っているような妄想に駆られる。PCが自分1人しか登場していないシーンで恐怖判定に失敗すると、自分に1D6点のダメージを与える（1回のみ）。",
                },
                {
                    madnessId: "nm-7",
                    version: "new",
                    world: "Classic",
                    titleJa: "誇大妄想",
                    titleEn: "Paranoia",
                    trigger: "自分以外の誰かがアイテムかプライズを獲得する。",
                    desc: "この世の中であなたほど尊いものはない。ほかのゴミ屑同然の連中が、あなたより優先されることなどありえない！原因人物の持っているアイテムかプライズを1個奪い、原因人物に1点のダメージを与える。",
                },
                {
                    madnessId: "nm-8",
                    version: "new",
                    world: "Classic",
                    titleJa: "死神",
                    titleEn: "Angel of Death",
                    trigger:
                        "誰か（自分を含む）の【生命力】が3点以下のとき、そのキャラクターの【生命力】が減少する。",
                    desc: "死は癒しだ。痛みや苦しみを抱える者がいれば、それを解放してあげたい。原因人物の【生命力】を1点減少する。",
                },
                {
                    madnessId: "nm-9",
                    version: "new",
                    world: "Classic",
                    titleJa: "虚言",
                    titleEn: "Pseudologia",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "どうしても人の興味がひきたくて、話を盛ったり、嘘を吐いたりしてしまう。自分が新たに【狂気】を公開するまで、自分の所持する【秘密】を誰かに譲渡したとき、そのショック欄が「全員」に変更されているものとして扱う。",
                },
                {
                    madnessId: "nm-10",
                    version: "new",
                    world: "Classic",
                    titleJa: "くいやみ",
                    titleEn: "Sarcasm",
                    trigger: "自分以外の誰かが判定に失敗する。",
                    desc: "心のささくれが常に刺激されている。悪口が止められない。自分が新たに【狂気】を公開するまで、自分がシーンに登場しているとき、自分以外のPCが主要な行動の判定に失敗するたび、そのPCの【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-11",
                    version: "new",
                    world: "Classic",
                    titleJa: "愚行",
                    titleEn: "Folly",
                    trigger: "自分が判定に成功する。",
                    desc: "あなたには、ちょっとした悪戯で目立ってみたいという欲求がある。自分の【居所】を、そのセッションに登場するキャラクター全員（シーンに登場していない者も含む）が獲得し、自分の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-12",
                    version: "new",
                    world: "Classic",
                    titleJa: "奇妙な欲求",
                    titleEn: "Strange Desire",
                    trigger: "即座。",
                    desc: "あなたには、とても口に出せない欲求がある。あなたが、そんなことをしたいと思っていることを知ったら、ほかの面々はどんな顔をするだろう？そのセッションの間、この【狂気】の持ち主の【秘密】か【精神状態】を獲得したPCは【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-13",
                    version: "new",
                    world: "Classic",
                    titleJa: "自己破壊",
                    titleEn: "Autocide",
                    trigger: "自分以外のPCがスペシャルを起こす。",
                    desc: "あなたは自分を憎んでいる。こんな自分など壊してしまいたい。自分に2点のダメージを与えるか、自分の【正気度】を2点減少する。",
                },
                {
                    madnessId: "nm-14",
                    version: "new",
                    world: "Classic",
                    titleJa: "陰謀論",
                    titleEn: "Conspiracy Theory",
                    trigger: "自分が調査の目標になる。",
                    desc: "あなたは何者かに監視されている。この国家的陰謀をみんなに教えなければ……。PCの中からランダムに1人を目標に選ぶ。目標の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-15",
                    version: "new",
                    world: "Classic",
                    titleJa: "行き詰まり",
                    titleEn: "Deadlock",
                    trigger: "即座。",
                    desc: "もうダメだ。何をやっても無駄なんだ。そのセッションの間、サイクルの終了時に《我慢》の判定を行う。失敗すると、自分の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-16",
                    version: "new",
                    world: "Classic",
                    titleJa: "気持ち悪い",
                    titleEn: "Creepy",
                    trigger: "自分以外の誰かが【狂気】を公開する。",
                    desc: "自分以外の人間がキモい。何を考えているか分からない。そのセッションの間、キャラクターを目標に調査や交流を行うと、自分の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-17",
                    version: "new",
                    world: "Classic",
                    titleJa: "絶叫",
                    titleEn: "Screaming",
                    trigger: "自分が恐怖判定に失敗する。",
                    desc: "事件の恐怖があなたをさいなむ。また何かあれば、恐ろしい絶叫をあげてしまうだろう。自分以外のPC全員を目標に選ぶ。目標は、知覚の分野からランダムに特技1つを選び、恐怖判定を行う。",
                },
                {
                    madnessId: "nm-18",
                    version: "new",
                    world: "Classic",
                    titleJa: "怪物",
                    titleEn: "Monster",
                    trigger: "自分がファンブルを起こす。",
                    desc: "あなたには怪物的な一面がある。これを知られるわけにはいかないが……。自分以外のPC全員を目標に選ぶ。目標は、怪異の分野からランダムに特技1つを選び、恐怖判定を行う。",
                },
                {
                    madnessId: "nm-19",
                    version: "new",
                    world: "Classic",
                    titleJa: "血への渇望",
                    titleEn: "Craving for Blood",
                    trigger: "自分がダメージを与える。",
                    desc: "あなたは思う存分、残虐に振る舞いたいと思っている。自分以外のPC全員を目標に選ぶ。目標は、暴力の分野からランダムに特技1つを選び、恐怖判定を行う。",
                },
                {
                    madnessId: "nm-20",
                    version: "new",
                    world: "Classic",
                    titleJa: "フェティッシュ",
                    titleEn: "Fetishism",
                    trigger: "自分がアイテムやプライズを獲得する。",
                    desc: "あなたは人造物への偏愛に目覚める。この新しい愛の形をみんなにも知って欲しい。自分以外のPC全員を目標に選ぶ。目標は、技術の分野からランダムに特技1つを選び、恐怖判定を行う。",
                },
                {
                    madnessId: "nm-21",
                    version: "new",
                    world: "Classic",
                    titleJa: "凶兆",
                    titleEn: "Omen",
                    trigger: "自分がシーンプレイヤーになる。",
                    desc: "破滅の予感がする。もう、おしまいなのかもしれない。自分は、ランダムに選んだ特技で恐怖判定を行う。",
                },
                {
                    madnessId: "nm-22",
                    version: "new",
                    world: "Classic",
                    titleJa: "いきすぎた想い",
                    titleEn: "Excessive Affection",
                    trigger: "自分が【感情】を獲得する。",
                    desc: "自分の中の気持ちが爆発しそうだ。自分以外のPC全員を目標に選ぶ。目標は、情動の分野からランダムに特技1つを選び、恐怖判定を行う。",
                },
                {
                    madnessId: "nm-23",
                    version: "new",
                    world: "Classic",
                    titleJa: "異言",
                    titleEn: "Glossolalia",
                    trigger: "自分が交流の目標になる。",
                    desc: "あなたは大宇宙の残酷な真実を知っている。これをみんなに話したいのだが……。自分以外のPC全員を目標に選ぶ。目標は、知識の分野からランダムに特技1つを選び、恐怖判定を行う。",
                },
                {
                    madnessId: "nm-24",
                    version: "new",
                    world: "Classic",
                    titleJa: "高慢と偏見",
                    titleEn: "Pride and Prejudice",
                    trigger: "自分以外の誰かが【狂気】を公開する。",
                    desc: "ああはなりたくない。自分の中にあるその気持ちを認めることができない。GMは、原因人物の持つ特技の中から好きな1つを選ぶ。自分は、その特技で恐怖判定を行う。",
                },
                {
                    madnessId: "nm-25",
                    version: "new",
                    world: "Classic",
                    titleJa: "広がる恐怖",
                    titleEn: "Pervasive Terror",
                    trigger: "誰か（自分を含む）がファンブルを起こす。",
                    desc: "あなたは、何もかもが怖くなってくる。自分の【恐怖心】の中から特技1つを選ぶ。そのセッションの間、その特技の上下左右の位置（ギャップを含まない）にある特技も【恐怖心】として扱う。",
                },
                {
                    madnessId: "nm-26",
                    version: "new",
                    world: "Classic",
                    titleJa: "恐怖症",
                    titleEn: "Phobia",
                    trigger: "自分が恐怖判定に失敗する。",
                    desc: "それを見るのも触るのも耐えられない。自分が新たに【狂気】を公開するまで、【正気度】を1点消費しないと【恐怖心】に指定されている特技を使用できない。",
                },
                {
                    madnessId: "nm-27",
                    version: "new",
                    world: "Classic",
                    titleJa: "恐怖の関連付け",
                    titleEn: "Link of Fear",
                    trigger: "誰か（自分を含む）が自分にダメージを与える。",
                    desc: "あなたは、あなたを傷つける者が怖い。そして、その人物に関連するすべてが怖くなる。そのセッションの間、原因人物の持つ特技すべてを自分の【恐怖心】として扱う。",
                },
                {
                    madnessId: "nm-28",
                    version: "new",
                    world: "Classic",
                    titleJa: "弱腰",
                    titleEn: "Wimp",
                    trigger: "誰か（自分を含む）が自分にダメージを与える。",
                    desc: "怖い。アレに近付きたくない。そのセッションの間、【正気度】を1点消費しないと、自分の【恐怖心】に指定されている特技を持っているキャラクターを攻撃や交流の目標に選ぶことができない。",
                },
                {
                    madnessId: "nm-29",
                    version: "new",
                    world: "Classic",
                    titleJa: "恐怖の足音",
                    titleEn: "Scary",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "震えが止まらない。恐怖が音を立てず背後へ忍び寄ってくるのを感じる。そのセッションの間、恐怖判定に失敗するたび、その恐怖判定の指定特技を自分の【恐怖心】として扱う。",
                },
                {
                    madnessId: "nm-30",
                    version: "new",
                    world: "Classic",
                    titleJa: "怯え",
                    titleEn: "Frightened",
                    trigger: "自分が恐怖判定に失敗する。",
                    desc: "やめてくれ。もう、ソレの話はやめてくれ！ 自分が新たに【狂気】を公開するまで、同じシーンにいるPCが、自分の【恐怖心】に指定されている特技を使用して判定を行うと、自分の【生命力】か【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-31",
                    version: "new",
                    world: "Classic",
                    titleJa: "気づき",
                    titleEn: "Insight",
                    trigger: "自分が調査によって【秘密】を獲得する。",
                    desc: "気づいてしまった。知りたくなかったのに……。そのセッションの間、トリガーの判定に使用した特技を【恐怖心】として扱う。噴出した場合、そのセッションの間、自分の修得している特技の中からランダムに選んだ1つを【恐怖心】として扱う。",
                },
                {
                    madnessId: "nm-32",
                    version: "new",
                    world: "Classic",
                    titleJa: "雑音",
                    titleEn: "Noise",
                    trigger: "自分が【秘密】を獲得する。",
                    desc: "頭の中で流れ続ける不快な音が、集中を邪魔する。そのセッションの間、特技の代用を行うとき、自分の【恐怖心】に指定された特技のマスは2マス分に数える。",
                },
                {
                    madnessId: "nm-33",
                    version: "new",
                    world: "Classic",
                    titleJa: "挙動不審",
                    titleEn: "Sketchy",
                    trigger: "自分が怪異によってダメージを受ける。",
                    desc: "あなたは、怪物から何かを伝染されたり、埋め込まれたという妄想にとりつかれている。そのセッションの間、調査判定と交流判定にマイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-34",
                    version: "new",
                    world: "Classic",
                    titleJa: "権力への不信",
                    titleEn: "Megalomania",
                    trigger: "誰かが自分の【秘密】か【居所】を獲得する。",
                    desc: "公権力はあなたを監視し、陰謀に巻き込もうとしている。やつらに近づいてはいけない！ そのセッションの間、調査判定と交流判定のファンブル値が1上昇する。",
                },
                {
                    madnessId: "nm-35",
                    version: "new",
                    world: "Classic",
                    titleJa: "盲目",
                    titleEn: "Darkness",
                    trigger: "自分が恐怖判定を行う。",
                    desc: "あなたの心は、これ以上怖いものを見るのを拒絶している。自分が新たに【狂気】を公開するまで、調査判定と命中判定にマイナス2の修正がつく。",
                },
                {
                    madnessId: "nm-36",
                    version: "new",
                    world: "Classic",
                    titleJa: "パニック",
                    titleEn: "Panic",
                    trigger: "自分がダメージを受ける。",
                    desc: "あなたは、暴力が恐ろしい。戦闘になると、その心はひどく動揺してしまう。自分が新たに【狂気】を公開するまで、戦闘中のファンブル値が1上昇する。",
                },
                {
                    madnessId: "nm-37",
                    version: "new",
                    world: "Classic",
                    titleJa: "正常性バイアス",
                    titleEn: "Normalcy Bias",
                    trigger: "自分が判定に失敗する。",
                    desc: "自分だけは大丈夫。たいしたことは起こっていないはずだ。自分が新たに【狂気】を公開するまで、命中判定と回避判定にマイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-38",
                    version: "new",
                    world: "Classic",
                    titleJa: "緊張",
                    titleEn: "Nervous",
                    trigger: "自分が戦闘に参加する。",
                    desc: "まずい！ 体がこわばる。何とかしないと、何とかしないと！ 次に自分がダメージを受けるまで、回避判定にマイナス2の修正がつく。",
                },
                {
                    madnessId: "nm-39",
                    version: "new",
                    world: "Classic",
                    titleJa: "幻覚",
                    titleEn: "Hallucination",
                    trigger: "自分がショックを受ける。",
                    desc: "ありえない声を聞き、見えるはずのないものが見える。なんなんだ、これは……？ そのセッションの間、知覚分野の特技が指定特技の判定は、マイナス2の修正がつく。",
                },
                {
                    madnessId: "nm-40",
                    version: "new",
                    world: "Classic",
                    titleJa: "なぜ自分だけ？",
                    titleEn: "Why only me?",
                    trigger: "自分の【生命力】か【正気度】が減少する。",
                    desc: "これ以上不幸な目にあいたくない。どうして自分だけ……みんなも同じ目にあえばいいのに。そのセッションの間、自分以外のPC全員は、自分と同じシーンに登場しているとき、回避判定にマイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-41",
                    version: "new",
                    world: "Classic",
                    titleJa: "言葉を失う",
                    titleEn: "Lose Words",
                    trigger: "誰かが自分に対して【感情】を獲得する。",
                    desc: "あなたは、強い感情を感じた。誰かと話すのが怖い。自分が新たに【狂気】を公開するまで、自分が【情報共有】によって【情報】を獲得できなくなり、ドラマシーン中、誰かに自発的に【情報】を譲渡できなくなる。",
                },
                {
                    madnessId: "nm-42",
                    version: "new",
                    world: "Classic",
                    titleJa: "現実逃避",
                    titleEn: "Detachment from Reality",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "あなたは現実から逃げ出したくてたまらない。自分が新たに【狂気】を公開するまで、自分の【正気度】が1点以上減少している場合、自分がシーンプレイヤーのときに休息判定以外の主要な行動を行うことができない。",
                },
                {
                    madnessId: "nm-43",
                    version: "new",
                    world: "Classic",
                    titleJa: "潔癖",
                    titleEn: "Fastidiousness",
                    trigger: "即座。",
                    desc: "他人に触れられるのが怖い！ 自分が新たに【狂気】を公開するまで、ドラマシーンにアイテムやプライズの譲渡・交換を行えなくなる。",
                },
                {
                    madnessId: "nm-44",
                    version: "new",
                    world: "Classic",
                    titleJa: "失踪",
                    titleEn: "Vanishing",
                    trigger:
                        "自分がファンブルを起こす。もしくは、自分が戦闘で敗者になる。",
                    desc: "ここは自分のいるべき場所じゃない。この【狂気】が顕在化したシーンが終わってから、2シーンの間、自分がシーンプレイヤーではないシーンに登場できなくなる（マスターシーンには登場可能）。",
                },
                {
                    madnessId: "nm-45",
                    version: "new",
                    world: "Classic",
                    titleJa: "いい人",
                    titleEn: "Convenience",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "人から嫌われたくない。そのため、つい都合のいい人になってしまう……。そのセッションの間、自分以外からシーンへの登場や自分の【居所】の譲渡を求められた場合、それを断ることができない。",
                },
                {
                    madnessId: "nm-46",
                    version: "new",
                    world: "Classic",
                    titleJa: "逃走",
                    titleEn: "Escape",
                    trigger: "自分が恐怖判定に失敗する。",
                    desc: "こんな場所にいたくない。逃げ出してしまいたい！ この【狂気】を公開したのがドラマシーンであれば、そのシーンから退場する。この【狂気】を公開したのが戦闘シーンであれば、次の自分の手番で【戦場移動】を使用する。",
                },
                {
                    madnessId: "nm-47",
                    version: "new",
                    world: "Classic",
                    titleJa: "行けたら行く",
                    titleEn: "I'll go if I can",
                    trigger: "自分の【生命力】が減少する。",
                    desc: "行こうとは思っている。でも足が動かないんだ。そのセッションの間、【正気度】を1点消費しないと、戦闘乱入を行ったり、特殊な戦闘乱入に挑戦したりできなくなる。",
                },
                {
                    madnessId: "nm-48",
                    version: "new",
                    world: "Classic",
                    titleJa: "悪夢",
                    titleEn: "Nightmare",
                    trigger: "自分が恐怖判定に失敗する。",
                    desc: "いつも悪夢にうなされる。あのときの事件が繰り返されるのだ。そのセッションの間、休息を行うとき、自分を目標に選ぶことができなくなる。",
                },
                {
                    madnessId: "nm-49",
                    version: "new",
                    world: "Classic",
                    titleJa: "記憶喪失",
                    titleEn: "Blackout",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "あなたは忘れたくて仕方のない辛い経験をしたようだ。自分の【秘密】と自分の【居所】以外の【情報】をすべて失う。",
                },
                {
                    madnessId: "nm-50",
                    version: "new",
                    world: "Classic",
                    titleJa: "ゴミ屋敷",
                    titleEn: "Hoarding House",
                    trigger: "自分がアイテムかプライズを獲得する。",
                    desc: "片付けられない。どうしても物を捨てられない。そのセッションの間、各サイクルの終了時にアイテムを1個以上持っていたら《整理》の判定を行う。失敗すると、持っているアイテムの中からランダムに選んだ1つを失う。",
                },
                {
                    madnessId: "nm-51",
                    version: "new",
                    world: "Classic",
                    titleJa: "かんしゃく",
                    titleEn: "Hot Temper",
                    trigger: "誰か（自分を含む）が判定に失敗する。",
                    desc: "何かイライラする。小さな不満が積み重なり、爆発しそうになる。いらいらいらいら……。自分の持っている好きなアイテム1つを失う。アイテムを持っていない場合、自分が1点のダメージを受ける。",
                },
                {
                    madnessId: "nm-52",
                    version: "new",
                    world: "Classic",
                    titleJa: "依存",
                    titleEn: "Reliance",
                    trigger: "自分が「鎮痛剤」を使用する。",
                    desc: "あなたは痛みに耐えられない。そのセッションの間、自分がシーンプレイヤーのシーンの終了時、自分の【生命力】か【正気度】が最大値でない場合、自分の「鎮痛剤」を1個使用する。",
                },
                {
                    madnessId: "nm-53",
                    version: "new",
                    world: "Classic",
                    titleJa: "失意",
                    titleEn: "Disappointment",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "突然、無気力になる。好きなものに興味が持てなくなった。自分が新たに【狂気】を公開するまで、【好奇心】の分野の特技の再挑戦が行えなくなり、【好奇心】の両隣になるギャップが塗りつぶされていないものとして扱う。",
                },
                {
                    madnessId: "nm-54",
                    version: "new",
                    world: "Classic",
                    titleJa: "劣等感",
                    titleEn: "Inferiority Complex",
                    trigger: "自分がファンブルを起こす。",
                    desc: "なんて自分はダメなんだろう。自信が失われていく。そのセッションの間、トリガーの判定に使用した特技を失う。噴出した場合、そのセッションの間、自分の修得している特技の中からランダムに選んだ1つが使用不能になる。",
                },
                {
                    madnessId: "nm-55",
                    version: "new",
                    world: "Classic",
                    titleJa: "罪の記憶",
                    titleEn: "Regret",
                    trigger: "自分が誰かにダメージを与える。",
                    desc: "あのときの感触が忘れられない。もう誰も傷つけたくない。こんなものがあるからいけないんだ。自分の「武器」をすべて失う。",
                },
                {
                    madnessId: "nm-56",
                    version: "new",
                    world: "Classic",
                    titleJa: "超現実主義",
                    titleEn: "Antioccultism",
                    trigger: "自分が恐怖判定に成功する。",
                    desc: "あなたは怪異を恐れるあまり、非科学的なものを異常なまでに否定している。自分の「お守り」をすべて失う。",
                },
                {
                    madnessId: "nm-57",
                    version: "new",
                    world: "Classic",
                    titleJa: "ひとめぼれ",
                    titleEn: "Love at First Sight",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "心がうずく。恋の予感。自分以外の好きなキャラクター1人を目標に選ぶ。目標に対する「愛情」の【感情】を獲得する。そのセッションの間、目標が自分以外の誰かにプラスの【感情】を獲得したり、行動不能になったりするたび、自分は【狂気】を1枚獲得する。",
                },
                {
                    madnessId: "nm-58",
                    version: "new",
                    world: "Classic",
                    titleJa: "狂信者",
                    titleEn: "Zealot",
                    trigger: "誰かが自分に対して【感情】を獲得する。",
                    desc: "運命の出会いが間近に迫っていることを感じる。原因人物に対して「狂信」の【感情】を獲得する。そのセッションの間、「狂信」を持っている相手を攻撃の目標に選ぶたび、自分の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-59",
                    version: "new",
                    world: "Classic",
                    titleJa: "服従",
                    titleEn: "Obedience",
                    trigger: "自分以外の誰かが自分にダメージを与える。",
                    desc: "あなたは自らの罪を隠して生きることに疲れている。その罪を罰してくれる人を求めている。原因人物に対して「忠誠」の【感情】を獲得する。そのセッションの間、「忠誠」を持っている相手が望まない判定には、マイナス2の修正がつく。",
                },
                {
                    madnessId: "nm-60",
                    version: "new",
                    world: "Classic",
                    titleJa: "人のせい",
                    titleEn: "Blaming Others",
                    trigger: "自分が判定に失敗する。",
                    desc: "何もかもうまくいかない。全部、あいつのせいだ！ 自分以外のPCの中からランダムに目標1人を選ぶ。「感情表」を使用して、目標に対してマイナスの【感情】を獲得する。",
                },
                {
                    madnessId: "nm-61",
                    version: "new",
                    world: "Classic",
                    titleJa: "暴露",
                    titleEn: "Divulgation",
                    trigger: "誰かが自分に対して【感情】を獲得する。",
                    desc: "友の欠点、過去の汚点、とっておきの醜聞……。我慢すればするほど言いたくなる。自分に対してプラスの【感情】を持っているキャラクター全員を目標に選ぶ。目標は「感情表」を使用して、その種類を決め直す。このとき、属性は必ずマイナスになる。",
                },
                {
                    madnessId: "nm-62",
                    version: "new",
                    world: "Classic",
                    titleJa: "異性への恐怖",
                    titleEn: "Isomerism Distrust",
                    trigger: "即座。",
                    desc: "異性が怖い。あいつらは怪物だ！ 自分が新たに【狂気】を公開するまで、異性キャラクターが登場しているシーンでは、自分の行う判定にマイナス1の修正がつき、ファンブル値が1上昇する。",
                },
                {
                    madnessId: "nm-63",
                    version: "new",
                    world: "Classic",
                    titleJa: "自己愛",
                    titleEn: "Narcissism",
                    trigger: "自分の【生命力】か【正気度】が回復する。",
                    desc: "みんなのことは嫌いじゃない。でも本当に好きなのは自分だけ。そのセッションの間、自分がプラスの【感情】を持っている相手に対して、感情修正を使用できなくなる。",
                },
                {
                    madnessId: "nm-64",
                    version: "new",
                    world: "Classic",
                    titleJa: "多重人格",
                    titleEn: "Multiple Personality",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "もう一つの人格が囁きかける。GMはマスターシーンを挿入して、この【狂気】を公開したPCの、もう一つの人格を自由に演出できる。そのマスターシーンに登場したキャラクターの中から目標1人を選ぶ。目標に2点のダメージを与えるか、目標に、この【狂気】を公開したPCに対する好きな【感情】を獲得させる。",
                },
                {
                    madnessId: "nm-65",
                    version: "new",
                    world: "Classic",
                    titleJa: "歪んだ心",
                    titleEn: "Distorted Mind",
                    trigger:
                        "自分以外の誰かが、自分を目標にした調査判定に成功する。",
                    desc: "あなたの精神は恐怖によって歪んでしまった。その歪みは、別の歪みを引き寄せる。そのセッションの間、この【狂気】の持ち主の【秘密】か【精神状態】を獲得したPCは【狂気】を1枚獲得する。",
                },
                {
                    madnessId: "nm-66",
                    version: "new",
                    world: "Classic",
                    titleJa: "予知夢",
                    titleEn: "Prediction Dream",
                    trigger: "即座。",
                    desc: "不思議な夢をみたことを思い出す。夢の中で異常な振る舞いを見せていた人がいた。あれは誰だったのか……？ 狂気の山札を上から5枚まで見て、その中から1枚を獲得する。そして、残りを好きな順番にして山札に戻す。",
                },
                {
                    madnessId: "nm-67",
                    version: "new",
                    world: "Classic",
                    titleJa: "マウント",
                    titleEn: "One-up",
                    trigger: "自分が判定に成功する。",
                    desc: "ついみんなに張り合って、無茶をしてしまう。各PCごとに顕在化した狂気の数を比べ、自分が最大でなかった場合、未公開の狂気の中から好きな1枚を公開する。そのとき、未公開の狂気が1枚もなければ、【狂気】を1枚獲得する。",
                },
                {
                    madnessId: "nm-68",
                    version: "new",
                    world: "Classic",
                    titleJa: "憔悴",
                    titleEn: "Drawdown",
                    trigger: "自分の【生命力】か【正気度】が減少する。",
                    desc: "体調や心の状態が優れない。抑制がきかなくなっている。思いつきを、そのまま行動に移してしまいそうだ。そのセッションの間、【狂気】のキャパシティの枚数が1減少する。",
                },
                {
                    madnessId: "nm-69",
                    version: "new",
                    world: "Classic",
                    titleJa: "変身願望",
                    titleEn: "Makeover Desire",
                    trigger: "自分以外のPCがスペシャルを起こす。",
                    desc: "自分が嫌いだ。もっと、みんなみたいになりたいのに。自分が新たに【狂気】を公開するまで、原因人物が公開している【狂気】の効果が自分に適用される（自分の顕在化している【狂気】の数が増えるわけではない）。",
                },
                {
                    madnessId: "nm-70",
                    version: "new",
                    world: "Classic",
                    titleJa: "加速",
                    titleEn: "Escalation",
                    trigger: "誰かが【狂気】を公開する。",
                    desc: "いいぞ！ 狂気の沙汰ほど面白い!! 自分が新たに【狂気】を公開するまで、自分が新たに獲得した【狂気】のトリガーが「即座」になる。クライマックスフェイズに、この【狂気】が公開された場合、クライマックスフェイズの間、この効果は続く。",
                },
                {
                    madnessId: "nm-71",
                    version: "new",
                    world: "Classic",
                    titleJa: "熱狂",
                    titleEn: "Enthusiasm",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "衝動と興奮が高みに引き上げる。自分の特技1つを選ぶ。そのセッションの間、その特技の判定のファンブル値が、顕在化している狂気の数だけ上昇する。そして、その特技の判定に顕在化している狂気の数だけプラスの修正がつく（上昇する値と修正は最大で3まで）。",
                },
                {
                    madnessId: "nm-72",
                    version: "new",
                    world: "Classic",
                    titleJa: "転移",
                    titleEn: "Folie a Deux",
                    trigger: "自分以外の誰かが【狂気】を公開する。",
                    desc: "まずい。伝染ったかな？ 原因人物の顕在化している【狂気】の中からランダムに1つを選ぶ。そのセッションの間、自分は、その【狂気】を公開し、顕在化したものとして扱う。",
                },
                {
                    madnessId: "nm-73",
                    version: "new",
                    world: "Classic",
                    titleJa: "彼岸への憧れ",
                    titleEn: "Empathy",
                    trigger: "自分が判定に失敗する。",
                    desc: "なぜだろう。怪異にひかれる自分がいる。GMは、そのシナリオに登場する怪異のエネミー1体を選ぶ。そのセッションの間、自分が【正気度】を1点減少するたび、その怪異の【生命力】を1点回復する。",
                },
                {
                    madnessId: "nm-74",
                    version: "new",
                    world: "Classic",
                    titleJa: "憑依",
                    titleEn: "Possession",
                    trigger: "自分がスペシャルかファンブルを起こす。",
                    desc: "憑かれたかな？ 悪魔か狐か犬神か……。この【狂気】が公開されたとき、GMは憑依した存在の名前を決める。自分が新たに【狂気】を公開するまで、GMが決めた名前以外の名前で自分のことを呼んだキャラクターに1点のダメージを与える。",
                },
                {
                    madnessId: "nm-75",
                    version: "new",
                    world: "Classic",
                    titleJa: "幽霊屋敷",
                    titleEn: "Haunted Mansion",
                    trigger: "即座。",
                    desc: "我が家は呪われている。自分の家なのに、心がまったく安まることがない。次に休息判定を行うと、そのセッションの間、自分の【生命力】と【正気度】の最大値を1点減少する。",
                },
                {
                    madnessId: "nm-76",
                    version: "new",
                    world: "Classic",
                    titleJa: "昏き者",
                    titleEn: "Dark One",
                    trigger:
                        "自分の【正気度】が3点以下のとき、自分の【正気度】が減少する。",
                    desc: "何かがあなたに話しかける。その声に従えば、何でもできる気がしてくる。そのセッションの間、回想シーンを行うと、通常の効果の代わりに【召喚】か【封印】のいずれか1つを使用できる。その効果の処理が終了した後に、自分は【狂気】を1枚獲得する。",
                },
                {
                    madnessId: "nm-77",
                    version: "new",
                    world: "Classic",
                    titleJa: "呼び声",
                    titleEn: "Calling",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "心の底では怪異を愛している。魔に逢いたいのだ。GMは【脅威度】が3以下の好きなエネミー1体を選ぶ。そのエネミーがそのシーンに登場する（戦闘シーンに登場した場合、次のラウンドの開始時から戦闘に参加し、戦闘参加者全員でプロットの処理を行う）。",
                },
                {
                    madnessId: "nm-78",
                    version: "new",
                    world: "Classic",
                    titleJa: "忌み数",
                    titleEn: "Unlucky Number",
                    trigger:
                        "誰か（自分を含む）が行った判定のサイコロの出目に4が含まれている。",
                    desc: "あなたは4という数字を恐れている。なぜなら4は死に通じているからだ。原因人物に2点のダメージを与える。",
                },
                {
                    madnessId: "nm-79",
                    version: "new",
                    world: "Classic",
                    titleJa: "闇からの祝福",
                    titleEn: "Eulogia from Darkness",
                    trigger: "自分が恐怖判定に失敗する。",
                    desc: "常人ならざる不思議な直感があなたを直撃する。好きなキャラクター1人を選んで、そのキャラクターの【情報】1つを獲得できる（この【情報】の獲得には「情報共有」が発生しない）。",
                },
                {
                    madnessId: "nm-80",
                    version: "new",
                    world: "Classic",
                    titleJa: "第四の壁",
                    titleEn: "Fourth Wall",
                    trigger:
                        "他のプレイヤーから自分のことをPC名ではなく、プレイヤー名で呼ばれる。",
                    desc: "もしかして、自分は物語の登場人物なのでは……？ 誰かが私たちが不幸になる様を見て楽しんでいるのでは……？ そのセッションの間、自分が行う欲求判定と交流判定にマイナス2の修正がつく。",
                },
                {
                    madnessId: "nm-81",
                    version: "new",
                    world: "JSHorror",
                    titleJa: "推し",
                    titleEn: "Stan",
                    trigger: "自分がプラスの【感情】を獲得する。",
                    desc: "湧き上がる愛。あなたこそが神。何かを捧げたい。そのセッションの間、サイクルの終了時、自分がプラスの【感情】を獲得しているキャラクターの中から1人を選び、自分の持っているアイテム1つを渡す。アイテムを渡せなかった場合、自分の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-82",
                    version: "new",
                    world: "JSHorror",
                    titleJa: "仮面",
                    titleEn: "Persona",
                    trigger: "即座。",
                    desc: "誰かと深く関わることへの恐れており、決して本心をみせないでいる。そのセッションの間、自分を目標にした調査判定と交流判定にマイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-83",
                    version: "new",
                    world: "JSHorror",
                    titleJa: "生きがいの喪失",
                    titleEn: "Feeling of Loss",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "今の仕事にやりがいを見いだせない。好きなことを仕事にできていない自分はよくないんじゃないか……。そのセッションの間、職能の判定にマイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-84",
                    version: "new",
                    world: "JSHorror",
                    titleJa: "さめる",
                    titleEn: "Getting the Ick",
                    trigger: "自分が【感情】を持っている相手が判定に失敗する。",
                    desc: "つながりの維持に重圧を感じている。関係をリセットしたい衝動にかられる。自分の原因人物に対する【感情】を失う。原因人物に対して【感情】を持っていなかった場合、自分の【正気度】を1点減少する。",
                },
                {
                    madnessId: "nm-85",
                    version: "new",
                    world: "20s",
                    titleJa: "蛮勇",
                    titleEn: "Brute Courage",
                    trigger: "自分が戦闘に勝利する。",
                    desc: "急に強い自信と自負が膨らんでくる。敵に背を見せるなど、負け犬のすることだ！ 自分が新たに【狂気】を公開するまで、戦闘から自発的に脱落することができなくなる。",
                },
                {
                    madnessId: "nm-86",
                    version: "new",
                    world: "20s",
                    titleJa: "禁酒",
                    titleEn: "Quit Drinking",
                    trigger: "自分が判定に失敗する。",
                    desc: "健康被害や治安悪化、家庭内暴力が増加している。飲酒は罪深い行為なのだ。そのセッションの間、「鎮痛剤」を使用して【正気度】を回復することができなくなる。",
                },
                {
                    madnessId: "nm-87",
                    version: "new",
                    world: "20s",
                    titleJa: "頑迷",
                    titleEn: "Bigotry",
                    trigger: "誰か（自分を含む）がファンブルを起こす。",
                    desc: "自動車やラジオのような新しい技術に不信感が生まれる。そのセッションの間、技術分野と知識分野の特技が指定特技の判定は、マイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-88",
                    version: "new",
                    world: "20s",
                    titleJa: "大量消費",
                    titleEn: "Mass Consumption",
                    trigger: "自分がアイテムを使用する。",
                    desc: "どんどん使え！ そのセッションの間、自分の持てるアイテムの合計数が、自分の顕在化している狂気の数までになる。この【狂気】を公開したとき、自分のアイテムの数が、顕在化している狂気の数より大きかった場合、その数になるようアイテムを失うこと。",
                },
                {
                    madnessId: "nm-89",
                    version: "new",
                    world: "Victoria",
                    titleJa: "階級心理",
                    titleEn: "Class Psychology",
                    trigger: "即座。",
                    desc: "あいつらは信用ならない。そのセッションの間、自分と異なる階級（上流、中流、労働者）のキャラクターを目標に交流を行う場合、マイナス2の修正がつく。階級が異なるかどうかは職業を基準にしてGMが判断すること。",
                },
                {
                    madnessId: "nm-90",
                    version: "new",
                    world: "Victoria",
                    titleJa: "迷信",
                    titleEn: "Aberglaube",
                    trigger: "自分が怪異に関する恐怖判定を行う。",
                    desc: "あなたはオカルトに熱狂し、傾倒している。そのセッションの間、知識分野の特技が指定特技の判定は、マイナス2の修正がつく。",
                },
                {
                    madnessId: "nm-91",
                    version: "new",
                    world: "Victoria",
                    titleJa: "儚い",
                    titleEn: "Ephemeral",
                    trigger: "誰か（自分を含む）が判定に失敗する。",
                    desc: "あなたは儚さやもろさを愛している。そのセッションの間、【正気度】が0点になった場合も行動不能になる。",
                },
                {
                    madnessId: "nm-92",
                    version: "new",
                    world: "Victoria",
                    titleJa: "吸血鬼妄想",
                    titleEn: "Vampire Freak",
                    trigger: "自分以外のPCがダメージを受ける。",
                    desc: "あなたは吸血鬼に憧れている。あのしたたる血潮を舐めとりたい。そのセッションの間、自分を交流判定の目標にしたり、自分が交流判定の目標にしたキャラクターは、【生命力】を1点減少する。",
                },
                {
                    madnessId: "nm-93",
                    version: "new",
                    world: "Loop",
                    titleJa: "既視感",
                    titleEn: "Nostalgia",
                    trigger: "自分が交流判定に成功する。",
                    desc: "あなたは、こんな風景を前にも見たことがあるような気がする。あなたは、この先、何が起きるか分かるような気がする。そのセッションの間、調査判定にプラス1の修正がつき、回避判定にマイナス1の修正がつく。",
                },
                {
                    madnessId: "nm-94",
                    version: "new",
                    world: "Loop",
                    titleJa: "未視感",
                    titleEn: "Jamais Vu",
                    trigger: "自分の【正気度】が減少する。",
                    desc: "日常見慣れたもののはずの道具だが、その使い方が分からない。これ、どう使うんだっけ？ 自分が新たに【狂気】を公開するまで、アイテムを使用したり、消費したりできなくなる（【依存】の【狂気】を公開している場合、「鎮痛剤」を持っていればそれを使用するが、特に効果はない）。",
                },
                {
                    madnessId: "nm-95",
                    version: "new",
                    world: "Loop",
                    titleJa: "望郷",
                    titleEn: "Nostalgia",
                    trigger: "ショックにより自分の【正気度】が減少する。",
                    desc: "ここは、あなたがいた場所とは違う世界な気がする。親も友人も、なぜかあなたが知っている人たちとは別人かのような気がする。早くあそこへ帰らないと！ そのセッションの間、休息判定と交流判定のファンブル値が1上昇する。",
                },
                {
                    madnessId: "nm-96",
                    version: "new",
                    world: "Loop",
                    titleJa: "虚無感",
                    titleEn: "Empty",
                    trigger: "自分の【生命力】が減少する。",
                    desc: "どれだけ苦労すれば報われるのだろう？ 永遠にこんなことを続けるのだろうか？ あなたは突然、虚無感に襲われる。以降、自分が再挑戦を行うためには、余分に【生命力】か【正気度】を1点消費しなければいけなくなる。",
                },
            ];

window.mockMadnessList = mockMadnessList